name: Working README Updater

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout with full history
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Create and switch to new branch
    - name: Create branch
      id: branch
      run: |
        timestamp=$(date +%Y%m%d-%H%M%S)
        branch_name="readme-update-$timestamp"
        git checkout -b "$branch_name"
        echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

    # 3. Modify README (with workspace path)
    - name: Update README
      run: |
        echo -e "\n<!-- Update -->\nTimestamp: $(date -u)" >> "$GITHUB_WORKSPACE/README.md"
        git add README.md
        git commit -m "Update README"

    # 4. Push changes
    - name: Push branch
      run: git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 5. Create PR (WITHOUT re-checkout)
    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
        # Critical: Prevent overwriting changes
        add-paths: README.md  
        commit-message: "Update README"
        branch: ${{ steps.branch.outputs.branch_name }}
        base: main
        title: "Update README - $(date +%m-%d)"
        body: "Automated update"
