name: Auto-update README with PR

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout main branch
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Create and switch to new branch
    - name: Create branch
      id: branch
      run: |
        timestamp=$(date +%Y%m%d-%H%M%S)
        branch_name="update-readme-$timestamp"
        git checkout -b "$branch_name"
        echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

    # 3. Make changes (with explicit path)
    - name: Update README
      run: |
        echo -e "\n<!-- Auto-updated -->\nLast run: $(date '+%Y-%m-%d %H:%M:%S %Z')\n" >> ./README.md
        cat ./README.md  # Verify changes
        git add .
        git status  # Should show "Changes to be committed"
        # git config --global user.name "GitHub Actions"
        # git config --global user.email "actions@github.com"
        git commit -m "Automated README update [skip ci]"
        git log -1  # Show the commit
        git push origin HEAD --force-with-lease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 6. Create PR (without auto-delete)
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.branch.outputs.branch_name }}
        base: main
        title: "docs: Update README ($(date '+%m-%d'))"
        body: |
          ### Automated Update
          - Timestamp: $(date)
          - Branch: ${{ steps.branch.outputs.branch_name }}
          - Approvers required
        labels: automated
        draft: false  # Change to 'true' if you want draft PRs

    # 7. Output PR/branch info
    - name: Show results
      run: |
        echo "New branch: ${{ steps.branch.outputs.branch_name }}"
        echo "PR Number: ${{ steps.create-pr.outputs.pull-request-number }}"
        echo "PR URL: https://github.com/$GITHUB_REPOSITORY/pull/${{ steps.create-pr.outputs.pull-request-number }}"
