name: Auto-update README

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout main branch
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Create new branch (from current main)
    - name: Create branch
      id: branch
      run: |
        timestamp=$(date +%Y%m%d-%H%M%S)
        branch_name="update-readme-$timestamp"
        git checkout -b "$branch_name"
        echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

    # 3. Modify README.md (in the new branch)
    - name: Update README
      run: |
        echo -e "\n<!-- Auto-updated -->\nLast run: $(date '+%Y-%m-%d %H:%M:%S %Z')\n" >> README.md
        git status  # Verify changes appear

    # 4. Commit changes
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions-bot@github.com"
        git add README.md
        git commit -m "Automated README update [skip ci]"
        git log -1  # Show latest commit

    # 5. Push the new branch
    - name: Push
      run: git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 6. Create PR (critical part you were missing)
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.branch.outputs.branch_name }}
        base: main
        title: "docs: Auto-update README ($(date '+%m-%d'))"
        body: |
          Automated update:
          - Added timestamp to README.md
          - Generated at $(date)
        labels: automated
        delete-branch: true  # Auto-deletes branch after merge
