name: Update README with timestamp

on:
  # schedule:
  #   - cron: '0 * * * *'  # Hourly
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main  # Explicitly checkout main

    - name: Create fresh branch
      id: branch
      run: |
        timestamp=$(date +%Y%m%d%H%M%S)
        branch_name="readme-update-$timestamp"
        git checkout -b $branch_name
        echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

    - name: Update README in new branch
      run: |
        # Add timestamp with clear separator
        echo -e "\n## Auto-Update Log\nLast run: $(date '+%Y-%m-%d %H:%M:%S %Z')\n" >> README.md
        cat README.md  # Verify changes

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "[Automated] Update README timestamp"

    - name: Push changes
      run: git push origin ${{ steps.branch.outputs.branch_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.branch.outputs.branch_name }}
        base: main
        title: "docs: Automated README update ($(date '+%m-%d'))"
        body: "Auto-generated PR updating README timestamp"
        labels: automated
